AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda function for saving data in db
Parameters:
  envType:
    Type: String
Resources:
  vehicleregistry:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: registration-number
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: registration-number
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  lambdaDb:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub db-${envType}
      Handler: db.lambda_handler
      Runtime: python3.8
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/db-lambda-execution-role
      Environment:
        Variables:
          VEHICLE_REGISTRY_TABLE_NAME: !Ref vehicleregistry